in this tutorial I am going to show you the quick tools to do all the previous operations using numpy!!

You can do everything using one command in numpy, This tutorial will show you the following:

h = f+g   to add vectors or matrices

np.ident(n) to create an identity matrix of size nxn

np.dot(u,v)  to compute the dot product of vectors u and v

np.matmul(A,x)  to compute the matrix vector multiplication Ax

np.matmul(A,B)  to compute the matrix matrix multiplication AB

In [12]:
#
import numpy as np

# create 2 vectors called f anf g, just give them some numbers.
f = np.array([1,2,4])
g = np.array([3,1,2])

print('f: ',f)
print('g: ',g)

# and now add the up and assign it to a variable called h

h = f+g

print('the sum is: ')
print(h)



f:  [1 2 4]
g:  [3 1 2]
the sum is: 
[4 3 6]


same thing for the matrix addition!


In [13]:
import numpy as np

# create two matrices as before
mat1 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
mat2 = np.array([[-1,-2,-3],[-4,-5,-6],[-7,-8,-9],[-10,-11,-12]])

# add them up! - note it should come to xeros with these two matrices
matsum = mat1+mat2
print('matrix sum')
print(matsum)


matrix sum
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


create an identity matrix of some size we use:

In [14]:
import numpy as np
# now compare your codes to using the numpy tools to do the above
# create a 5x5 identity matrix
im = np.identity(5)
print('identity matrix')
print(im)



identity matrix
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


and what about dot products of vectors:

In [15]:
# do a dot product
u = np.array([6,4,3,5,4])
v = np.array([1,2,2,3,4])
dp = np.dot(u,v)
print('numpy dot product is ',dp)



numpy dot product is  51


finally the matrix vector and matrix -matrix multiplications can be performed in one command


In [16]:
# create two matrices
A = np.array([[4,2,1],[1,3,1],[2,3,6]])
B = np.array([[4,2,1],[1,3,1],[2,3,6]])
# and some vector x
x = np.array([4,3,2])

# the matrix vector product can be computed by:
b = np.matmul(A,x)
print('matrix vector mult')
print(b)

# the matrix matrix product can be computed using the same command:

C = np.matmul(A,B)
print('matrix matrix mult')
print(C)


matrix vector mult
[24 15 29]
matrix matrix mult
[[20 17 12]
 [ 9 14 10]
 [23 31 41]]
