In this tutorial we are going to look at creating matrices using numpy and change, add, print their values together.

Here you will learn the commands:

np.array()  - to create an matrix with defined numbers

np.zeros([n,m]) - to create a matrix of size nxm with zeros 


To start let's create 2 matrices of size 4 by 3 with some pre-defined values, then change some of the matrix values (to show you how this is done). We will then add them together.

In [5]:
# as always, load up the numpy as np
import numpy as np

# set up two 4x3 matrices 
# we use the np.array() command, and include in the [] the values
# of the matrices.
# IMPORTANT! look at the [] structure below. we have:
# [[row 1],[row2],[row3],...,[rowN]]
mat1 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
mat2 = np.array([[-1,-2,-3],[-4,-5,-6],[-7,-8,-9],[-10,-11,-12]])

# print the matrices, make sure they are right!
print('mat1 matrix values are ')
print(mat1)
print('mat2 matrix values are')
print(mat2)

# print some individual components out 
# to access i.j element of the matrix we use, for example, mat1[i,j]
# just remember the indexing starts at zero!
print('printing out some individual elements of the matrix:')
print(mat1[0,0])
print(mat2[1,1])


# change some numbers just to get used to this. 
# remember, again, the indexing starts at 0
# and the i,j component in the matrix is mat1[i,j]
# so to change some number we use:
mat1[0,0] = 100
mat1[1,1] = -100
mat1[0,2] = 0

# print and check!
print('the new mat1 matrix values are:')
print(mat1)

# now set up a new matrix of size 4x3 and add mat1 and mat2 together.
# use np.zeros to create
mat3 = np.zeros([4,3])
# and a double loop for the adding
for i in range(4):
    for j in range(3):
        mat3[i,j] = mat1[i,j]+mat2[i,j]

print('the sum of matrix mat1 and mat2 is:')
print(mat3)
# check to see it is correct!


mat1 matrix values are 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
mat2 matrix values are
[[ -1  -2  -3]
 [ -4  -5  -6]
 [ -7  -8  -9]
 [-10 -11 -12]]
printing out some individual elements of the matrix:
1
-5
the new mat1 matrix values are:
[[ 100    2    0]
 [   4 -100    6]
 [   7    8    9]
 [  10   11   12]]
the sum of matrix mat1 and mat2 is:
[[  99.    0.   -3.]
 [   0. -105.    0.]
 [   0.    0.    0.]
 [   0.    0.    0.]]


your go now. create a 3x3 matrix and turn it into an identity matix

To start you off, I will set up a matrix with initial values of zeros - using the np.zeros() command


In [6]:
import numpy as np

# make a 3x3 matrix called mat
mat = np.zeros([3,3])
print('initial matrix')
print(mat)

# you fill in the rest. to make it diagonal. 
#See if you can use a loop to do this.


initial matrix
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
