Q1: complete the code to form the identity matrix using a single loop


In [5]:
import numpy as np

matrix = np.zeros([5,5])
print('initial matrix')
print(matrix)

# write a loop to form the idenity matrix

# print it out
print('identity matrix')
print(matrix)



initial matrix
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
identity matrix
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Q2:
write a piece of code do perform the dot product of 2 vectors. i.e. given vectors u and v perform u.v 

In [3]:
import numpy as np

u = np.array([6,4,3,5,4])
v = np.array([1,2,2,3,4])

# complete the code to do the dot porduct.



numpy dot product is  51


Q3: write the code to perform the matrix vector multiplication b = Ax

In [6]:
import numpy as np
# set up the matrix and vector
A = np.array([[4,2,1],[1,3,1],[2,3,6]])
x = np.array([4,3,2])

# write your code here. create a vector b and calculate the values 




Q4: compute the matrix-matrix multiplication of A and B below - not the dimensions I have set!



In [4]:
import numpy as np
# set up the matrix and vector
A = np.array([[4,2,1],[1,3,1],[2,3,6]])
B = np.array([[4,3],[4,5],[1,1]])

print('A:')
print(A)

print('B:')
print(B)

# you do the rest.


A:
[[4 2 1]
 [1 3 1]
 [2 3 6]]
B:
[[4 3]
 [4 5]
 [1 1]]
