Q1: complete the code to form the identity matrix using a single loop


In [17]:
import numpy as np

matrix = np.zeros([5,5])
print('initial matrix')
print(matrix)

print(matrix.shape) # shows the dimensions of the matrix with 5 rows and 5 columns

for i in range(matrix.shape[0]): # from 0 to the length of the rows i.e. range(5)
    matrix[i][i] = 1 # diagonal at (0,0), (1,1), (2,2), etc i.e. row = column
print(matrix)
    

initial matrix
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
(5, 5)
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Q2:
write a piece of code do perform the dot product of 2 vectors. i.e. given vectors u and v perform u.v 

In [14]:
import numpy as np

u = np.array([6,4,3,5,4])
v = np.array([1,2,2,3,4])

# complete the code to do the dot product
dotp = 0
for i in range(u.shape[0]): # same as for i in range(v.shape[0]) as the dimensions of both vectors are the same
    dotp += u[i] * v[i] # sums the product of each element
print(dotp)


51


Q3: write the code to perform the matrix vector multiplication b = Ax

$ A = \begin{bmatrix}
4 & 2 & 1\\ 
1 & 3 & 1\\ 
2 & 3 & 6
\end{bmatrix},  x = \begin{bmatrix}
4 \\ 
3 \\ 
2 \\
\end{bmatrix}$

Multiplying each row of matrix A by the row vector x.

$ \therefore b = \begin{bmatrix}
24\\ 
15\\ 
29
\end{bmatrix} $

In [2]:
import numpy as np
# set up the matrix and vector
A = np.array([[4,2,1],[1,3,1],[2,3,6]])
x = np.array([[4],[3],[2]])

Row=A.shape[0] # A.shape will find the total number of rows
Column=A.shape[1] # A.shape will find the total number of colums

## write your code here. create a vector b and calculate the values 
b = np.zeros([3,1])
for i in range(Row): # iterating through rows
    for j in range(Column): # iterating through columns
        b[i] += A[i][j] * x[j] 
print(b)

[[24.]
 [15.]
 [29.]]


Q4: compute the matrix-matrix multiplication of A and B below - not the dimensions I have set!



$ A \cdot B = \begin{bmatrix}
4 & 2 & 1\\ 
1 & 3 & 1\\ 
2 & 3 & 6
\end{bmatrix} \cdot 
\begin{bmatrix}
4 & 3 \\ 
4 & 5 \\ 
1 & 1 
\end{bmatrix} = 
\begin{bmatrix}
25 & 23 \\ 
17 & 19\\ 
26 & 27 
\end{bmatrix} $

In [16]:
import numpy as np
# set up the matrix and vector
A = np.array([[4,2,1],[1,3,1],[2,3,6]])
B = np.array([[4,3],[4,5],[1,1]])

print('A:')
print(A)

print('B:')
print(B)

# multiplying (3 x 3) matrix with (3 x 2) matrix, resulting matrix will be (3 x 2)
# creating an empty matrix
prod = np.zeros([3,2])

for i in range(A.shape[0]): # iterating through rows of A
    for j in range(B.shape[1]): # iterating through columns of B
        for k in range(B.shape[0]): # iterating through rows of B
            prod[i][j] += A[i][k] * B[k][j] # finding the dot product to get resultant matrix element
print(prod)

A:
[[4 2 1]
 [1 3 1]
 [2 3 6]]
B:
[[4 3]
 [4 5]
 [1 1]]
[[25. 23.]
 [17. 19.]
 [26. 27.]]
